services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Introduction\EventListener\AfterExtensionSiteFilesHaveBeenImportedEventListener:
    tags:
      - name: event.listener
        identifier: 'configureSiteListener'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionSiteFilesHaveBeenImportedEvent
