name: Tests

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *'

jobs:
  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']
        dependencies: ['stable']
        experimental: [false]
        include:
          - php-version: '8.1'
            dependencies: 'highest'
            experimental: true
          - php-version: '8.2'
            dependencies: 'highest'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Setup PHP
        run: ddev config --php-version ${{ matrix.php-version }}

      - name: Use dev releases for latest-deps builds to catch problems earlier
        if: ${{ matrix.dependencies == 'highest' }}
        run: ddev composer config prefer-stable false

      - name: Run Acceptance Tests
        run: ddev run-tests acceptance
