name: Tests

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  acceptance_tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      - name: Run Acceptance Tests
        run: ddev run-tests acceptance
